services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py

  frontend:
    build:
      context: ./FRONT_END
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend